<?php

declare(strict_types=1);

namespace pocketmine\network\bedrock\protocol\types;

/**
 * Particle string IDs used by SpawnParticleEffectPacket.
 * This file is automatically generated out of game assets.
 */
interface ParticleEffectIds{

	public const ARROWSPELL = "minecraft:arrow_spell_emitter";
	public const BALLOON_GAS = "minecraft:balloon_gas_particle";
	public const BASIC_BUBBLE = "minecraft:basic_bubble_particle";
	public const BASIC_BUBBLE_MANUAL = "minecraft:basic_bubble_particle_manual";
	public const BASIC_CRIT = "minecraft:basic_crit_particle";
	public const BASIC_FLAME = "minecraft:basic_flame_particle";
	public const BASIC_PORTAL = "minecraft:basic_portal_particle";
	public const BASIC_SMOKE = "minecraft:basic_smoke_particle";
	public const BLEACH = "minecraft:bleach";
	public const BLOCK_DESTRUCT = "minecraft:block_destruct";
	public const BUBBLE_COLUMN_BUBBLE = "minecraft:bubble_column_bubble";
	public const BUBBLE_COLUMN_DOWN = "minecraft:bubble_column_down_particle";
	public const BUBBLE_COLUMN_UP = "minecraft:bubble_column_up_particle";
	public const CAMERA_SHOOT_EXPLOSION = "minecraft:camera_shoot_explosion";
	public const CAMPFIRE_SMOKE = "minecraft:campfire_smoke_particle";
	public const CAMPFIRE_SMOKE_TALL = "minecraft:campfire_tall_smoke_particle";
	public const CAULDRON_BUBBLE = "minecraft:cauldron_bubble_particle";
	public const CAULDRON_SPLASH = "minecraft:cauldron_splash_particle";
	public const CAULDRONSPELL = "minecraft:cauldron_spell_emitter";
	public const COLORED_FLAME = "minecraft:colored_flame_particle";
	public const CONDUIT_ABSORB = "minecraft:conduit_absorb_particle";
	public const CONDUIT_ATTACK = "minecraft:conduit_attack_emitter";
	public const CRITICAL_HIT = "minecraft:critical_hit_emitter";
	public const DOLPHIN_MOVE = "minecraft:dolphin_move_particle";
	public const DRAGON_DEATH_EXPLOSION = "minecraft:dragon_death_explosion_emitter";
	public const DRAGON_DESTROY_BLOCK = "minecraft:dragon_destroy_block";
	public const DRAGON_DYING_EXPLOSION = "minecraft:dragon_dying_explosion";
	public const ENCHANTING_TABLE_PARTICLE = "minecraft:enchanting_table_particle";
	public const END_CHEST = "minecraft:end_chest";
	public const ENDROD = "minecraft:endrod";
	public const EVAPORATION_ELEPHANT_TOOTHPASTE = "minecraft:elephant_tooth_paste_vapor_particle";
	public const EVOCATION_FANG = "minecraft:evocation_fang_particle";
	public const EVOKER_SPELL = "minecraft:evoker_spell";
	public const EXPLOSION_CAULDRON = "minecraft:cauldron_explosion_emitter";
	public const EXPLOSION_DEATH = "minecraft:death_explosion_emitter";
	public const EXPLOSION_EGG_DESTROY = "minecraft:egg_destroy_emitter";
	public const EXPLOSION_EYEOFENDER_DEATH = "minecraft:eyeofender_death_explode_particle";
	public const EXPLOSION_LABTABLE_FIRE = "minecraft:misc_fire_vapor_particle";
	public const EXPLOSION_LEVEL = "minecraft:explosion_particle";
	public const EYE_OF_ENDER_BUBBLE = "minecraft:eye_of_ender_bubble_particle";
	public const FALLING_BORDER_DUST = "minecraft:falling_border_dust_particle";
	public const FALLING_DUST_CONCRETE_POWDER = "minecraft:falling_dust_concrete_powder_particle";
	public const FALLING_DUST_DRAGON_EGG = "minecraft:falling_dust_dragon_egg_particle";
	public const FALLING_DUST_GRAVEL = "minecraft:falling_dust_gravel_particle";
	public const FALLING_DUST_RED_SAND = "minecraft:falling_dust_red_sand_particle";
	public const FALLING_DUST_SAND = "minecraft:falling_dust_sand_particle";
	public const FALLING_DUST_SCAFFOLDING = "minecraft:falling_dust_scaffolding_particle";
	public const FALLING_DUST_TOP_SNOW = "minecraft:falling_dust_top_snow_particle";
	public const FISH_HOOK = "minecraft:fish_hook_particle";
	public const FISH_POS = "minecraft:fish_pos_particle";
	public const GUARDIAN_ATTACK = "minecraft:guardian_attack_particle";
	public const GUARDIAN_WATER_MOVE = "";
	public const HEART = "minecraft:heart_particle";
	public const HUGE_EXPLOSION_LAB_MISC = "minecraft:huge_explosion_lab_misc_emitter";
	public const HUGE_EXPLOSION_LEVEL = "minecraft:huge_explosion_emitter";
	public const ICE_EVAPORATION = "minecraft:ice_evaporation_emitter";
	public const INK = "minecraft:ink_emitter";
	public const KNOCKBACK_ROAR = "minecraft:knockback_roar_particle";
	public const LAB_TABLE_HEATBLOCK_DUST = "minecraft:lab_table_heatblock_dust_particle";
	public const LAB_TABLE_MISC_MYSTICAL = "minecraft:lab_table_misc_mystical_particle";
	public const LARGE_EXPLOSION_LEVEL = "minecraft:large_explosion";
	public const LAVA_DRIP = "minecraft:lava_drip_particle";
	public const LAVA_PARTICLE = "minecraft:lava_particle";
	public const LLAMA_SPIT = "minecraft:llama_spit_smoke";
	public const MAGNESIUM_SALTS = "minecraft:magnesium_salts_emitter";
	public const MOB_BLOCK_SPAWN = "minecraft:mob_block_spawn_emitter";
	public const MOB_PORTAL = "minecraft:mob_portal";
	public const MOBFLAME = "minecraft:mobflame_emitter";
	public const MOBSPELL = "minecraft:mobspell_emitter";
	public const MYCELIUM_DUST = "minecraft:mycelium_dust_particle";
	public const NOTE = "minecraft:note_particle";
	public const OBSIDIAN_GLOW_DUST = "minecraft:obsidian_glow_dust_particle";
	public const PHANTOM_TRAIL = "minecraft:phantom_trail_particle";
	public const PORTAL_DIRECTIONAL = "minecraft:portal_directional";
	public const PORTAL_EAST_WEST = "minecraft:portal_east_west";
	public const PORTAL_NORTH_SOUTH = "minecraft:portal_north_south";
	public const RAIN_SPLASH = "minecraft:rain_splash_particle";
	public const REDSTONE_ORE_DUST = "minecraft:redstone_ore_dust_particle";
	public const REDSTONE_REPEATER_DUST = "minecraft:redstone_repeater_dust_particle";
	public const REDSTONE_TORCH_DUST = "minecraft:redstone_torch_dust_particle";
	public const REDSTONE_WIRE_DUST = "minecraft:redstone_wire_dust_particle";
	public const RISING_BORDER_DUST = "minecraft:rising_border_dust_particle";
	public const SHULKER_BULLET = "minecraft:shulker_bullet";
	public const SILVERFISH_GRIEF = "minecraft:silverfish_grief_emitter";
	public const SPLASHPOTIONSPELL = "minecraft:splash_spell_emitter";
	public const SPONGE_ABSORB_BUBBLE = "minecraft:sponge_absorb_water_particle";
	public const SQUID_FLEE = "minecraft:squid_flee_particle";
	public const SQUID_INK_BUBBLE = "minecraft:squid_ink_bubble";
	public const SQUID_MOVE = "minecraft:squid_move_particle";
	public const STUNNED = "minecraft:stunned_emitter";
	public const TOTEM = "minecraft:totem_particle";
	public const UNDERWATER_TORCH_BUBBLE = "minecraft:underwater_torch_particle";
	public const VILLAGER_ANGRY = "minecraft:villager_angry";
	public const VILLAGER_HAPPY = "minecraft:villager_happy";
	public const WATER_DRIP = "minecraft:water_drip_particle";
	public const WATER_EVAPORATION_ACTOR = "minecraft:water_evaporation_actor_emitter";
	public const WATER_EVAPORATION_BUCKET = "minecraft:water_evaporation_bucket_emitter";
	public const WATER_SPASH_MANUAL = "minecraft:water_splash_particle_manual";
	public const WATER_SPLASH = "minecraft:water_splash_particle";
	public const WATER_WAKE = "minecraft:water_wake_particle";
	public const WITHER_BOSS_INVULNERABLE = "minecraft:wither_boss_invulnerable";

}