<?php

/*
 *
 *  _____   _____   __   _   _   _____  __    __  _____
 * /  ___| | ____| |  \ | | | | /  ___/ \ \  / / /  ___/
 * | |     | |__   |   \| | | | | |___   \ \/ /  | |___
 * | |  _  |  __|  | |\   | | | \___  \   \  /   \___  \
 * | |_| | | |___  | | \  | | |  ___| |   / /     ___| |
 * \_____/ |_____| |_|  \_| |_| /_____/  /_/     /_____/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author iTX Technologies
 * @link https://itxtech.org
 *
 */

namespace pocketmine\level\generator\object;

use pocketmine\block\Block;
use pocketmine\block\Leaves2;
use pocketmine\block\Wood2;
use pocketmine\level\ChunkManager;
use pocketmine\utils\Random;

class DarkOakTree extends Tree {
	/**
	 * DarkOakTree constructor.
	 */
	public function __construct(){
		$this->trunkBlock = Block::WOOD2;
		$this->leafBlock = Block::LEAVES2;
		$this->leafType = Leaves2::DARK_OAK;
		$this->type = Wood2::DARK_OAK;
		$this->treeHeight = 8;
	}
   public function placeObject(ChunkManager $level, $x, $y, $z, Random $random){
	$this->level = $level;
$this->level->setBlockIdAt($x + (-4), $y + (4), $z + (0), 18);
$this->level->setBlockDataAt($x + (-4), $y + (4), $z + (0), 13);
$this->level->setBlockIdAt($x + (-4), $y + (5), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-4), $y + (5), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-3), $y + (3), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-3), $y + (3), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-3), $y + (4), $z + (2), 18);
$this->level->setBlockDataAt($x + (-3), $y + (4), $z + (2), 13);
$this->level->setBlockIdAt($x + (-3), $y + (5), $z + (-2), 18);
$this->level->setBlockDataAt($x + (-3), $y + (5), $z + (-2), 13);
$this->level->setBlockIdAt($x + (-3), $y + (5), $z + (0), 18);
$this->level->setBlockDataAt($x + (-3), $y + (5), $z + (0), 13);
$this->level->setBlockIdAt($x + (-3), $y + (6), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-3), $y + (6), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-3), $y + (6), $z + (1), 18);
$this->level->setBlockDataAt($x + (-3), $y + (6), $z + (1), 13);
$this->level->setBlockIdAt($x + (-3), $y + (6), $z + (2), 18);
$this->level->setBlockDataAt($x + (-3), $y + (6), $z + (2), 13);
$this->level->setBlockIdAt($x + (-3), $y + (7), $z + (0), 18);
$this->level->setBlockDataAt($x + (-3), $y + (7), $z + (0), 13);
$this->level->setBlockIdAt($x + (-3), $y + (9), $z + (0), 18);
$this->level->setBlockDataAt($x + (-3), $y + (9), $z + (0), 13);
$this->level->setBlockIdAt($x + (-2), $y + (2), $z + (2), 18);
$this->level->setBlockDataAt($x + (-2), $y + (2), $z + (2), 13);
$this->level->setBlockIdAt($x + (-2), $y + (3), $z + (-2), 18);
$this->level->setBlockDataAt($x + (-2), $y + (3), $z + (-2), 13);
$this->level->setBlockIdAt($x + (-2), $y + (3), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-2), $y + (3), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-2), $y + (3), $z + (0), 18);
$this->level->setBlockDataAt($x + (-2), $y + (3), $z + (0), 13);
$this->level->setBlockIdAt($x + (-2), $y + (3), $z + (1), 18);
$this->level->setBlockDataAt($x + (-2), $y + (3), $z + (1), 13);
$this->level->setBlockIdAt($x + (-2), $y + (4), $z + (0), 18);
$this->level->setBlockDataAt($x + (-2), $y + (4), $z + (0), 13);
$this->level->setBlockIdAt($x + (-2), $y + (5), $z + (-2), 18);
$this->level->setBlockDataAt($x + (-2), $y + (5), $z + (-2), 13);
$this->level->setBlockIdAt($x + (-2), $y + (5), $z + (2), 18);
$this->level->setBlockDataAt($x + (-2), $y + (5), $z + (2), 13);
$this->level->setBlockIdAt($x + (-2), $y + (6), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-2), $y + (6), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-2), $y + (6), $z + (0), 18);
$this->level->setBlockDataAt($x + (-2), $y + (6), $z + (0), 13);
$this->level->setBlockIdAt($x + (-2), $y + (6), $z + (1), 18);
$this->level->setBlockDataAt($x + (-2), $y + (6), $z + (1), 13);
$this->level->setBlockIdAt($x + (-2), $y + (6), $z + (3), 18);
$this->level->setBlockDataAt($x + (-2), $y + (6), $z + (3), 13);
$this->level->setBlockIdAt($x + (-2), $y + (7), $z + (-2), 18);
$this->level->setBlockDataAt($x + (-2), $y + (7), $z + (-2), 13);
$this->level->setBlockIdAt($x + (-2), $y + (8), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-2), $y + (8), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-2), $y + (8), $z + (0), 18);
$this->level->setBlockDataAt($x + (-2), $y + (8), $z + (0), 13);
$this->level->setBlockIdAt($x + (-2), $y + (8), $z + (2), 18);
$this->level->setBlockDataAt($x + (-2), $y + (8), $z + (2), 13);
$this->level->setBlockIdAt($x + (-2), $y + (9), $z + (1), 18);
$this->level->setBlockDataAt($x + (-2), $y + (9), $z + (1), 13);
$this->level->setBlockIdAt($x + (-2), $y + (10), $z + (0), 18);
$this->level->setBlockDataAt($x + (-2), $y + (10), $z + (0), 13);
$this->level->setBlockIdAt($x + (-2), $y + (11), $z + (1), 18);
$this->level->setBlockDataAt($x + (-2), $y + (11), $z + (1), 13);
$this->level->setBlockIdAt($x + (-2), $y + (12), $z + (0), 18);
$this->level->setBlockDataAt($x + (-2), $y + (12), $z + (0), 13);
$this->level->setBlockIdAt($x + (-2), $y + (15), $z + (0), 18);
$this->level->setBlockDataAt($x + (-2), $y + (15), $z + (0), 13);
$this->level->setBlockIdAt($x + (-1), $y + (2), $z + (-3), 18);
$this->level->setBlockDataAt($x + (-1), $y + (2), $z + (-3), 13);
$this->level->setBlockIdAt($x + (-1), $y + (3), $z + (-2), 18);
$this->level->setBlockDataAt($x + (-1), $y + (3), $z + (-2), 13);
$this->level->setBlockIdAt($x + (-1), $y + (3), $z + (1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (3), $z + (1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (3), $z + (2), 18);
$this->level->setBlockDataAt($x + (-1), $y + (3), $z + (2), 13);
$this->level->setBlockIdAt($x + (-1), $y + (3), $z + (3), 18);
$this->level->setBlockDataAt($x + (-1), $y + (3), $z + (3), 13);
$this->level->setBlockIdAt($x + (-1), $y + (4), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (4), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (4), $z + (0), 18);
$this->level->setBlockDataAt($x + (-1), $y + (4), $z + (0), 13);
$this->level->setBlockIdAt($x + (-1), $y + (4), $z + (1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (4), $z + (1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (5), $z + (-3), 18);
$this->level->setBlockDataAt($x + (-1), $y + (5), $z + (-3), 13);
$this->level->setBlockIdAt($x + (-1), $y + (6), $z + (-2), 18);
$this->level->setBlockDataAt($x + (-1), $y + (6), $z + (-2), 13);
$this->level->setBlockIdAt($x + (-1), $y + (6), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (6), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (6), $z + (0), 18);
$this->level->setBlockDataAt($x + (-1), $y + (6), $z + (0), 13);
$this->level->setBlockIdAt($x + (-1), $y + (6), $z + (1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (6), $z + (1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (6), $z + (3), 18);
$this->level->setBlockDataAt($x + (-1), $y + (6), $z + (3), 13);
$this->level->setBlockIdAt($x + (-1), $y + (7), $z + (2), 18);
$this->level->setBlockDataAt($x + (-1), $y + (7), $z + (2), 13);
$this->level->setBlockIdAt($x + (-1), $y + (8), $z + (-2), 18);
$this->level->setBlockDataAt($x + (-1), $y + (8), $z + (-2), 13);
$this->level->setBlockIdAt($x + (-1), $y + (8), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (8), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (9), $z + (0), 18);
$this->level->setBlockDataAt($x + (-1), $y + (9), $z + (0), 13);
$this->level->setBlockIdAt($x + (-1), $y + (9), $z + (1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (9), $z + (1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (9), $z + (2), 18);
$this->level->setBlockDataAt($x + (-1), $y + (9), $z + (2), 13);
$this->level->setBlockIdAt($x + (-1), $y + (10), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (10), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (10), $z + (1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (10), $z + (1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (11), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (11), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (11), $z + (0), 18);
$this->level->setBlockDataAt($x + (-1), $y + (11), $z + (0), 13);
$this->level->setBlockIdAt($x + (-1), $y + (12), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (12), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (12), $z + (1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (12), $z + (1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (13), $z + (0), 18);
$this->level->setBlockDataAt($x + (-1), $y + (13), $z + (0), 13);
$this->level->setBlockIdAt($x + (-1), $y + (13), $z + (1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (13), $z + (1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (14), $z + (-1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (14), $z + (-1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (15), $z + (1), 18);
$this->level->setBlockDataAt($x + (-1), $y + (15), $z + (1), 13);
$this->level->setBlockIdAt($x + (-1), $y + (16), $z + (0), 18);
$this->level->setBlockDataAt($x + (-1), $y + (16), $z + (0), 13);
$this->level->setBlockIdAt($x + (-1), $y + (18), $z + (0), 18);
$this->level->setBlockDataAt($x + (-1), $y + (18), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (0), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (0), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (1), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (1), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (2), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (2), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (3), $z + (-3), 18);
$this->level->setBlockDataAt($x + (0), $y + (3), $z + (-3), 13);
$this->level->setBlockIdAt($x + (0), $y + (3), $z + (-2), 18);
$this->level->setBlockDataAt($x + (0), $y + (3), $z + (-2), 13);
$this->level->setBlockIdAt($x + (0), $y + (3), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (3), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (3), $z + (3), 18);
$this->level->setBlockDataAt($x + (0), $y + (3), $z + (3), 13);
$this->level->setBlockIdAt($x + (0), $y + (4), $z + (-1), 18);
$this->level->setBlockDataAt($x + (0), $y + (4), $z + (-1), 13);
$this->level->setBlockIdAt($x + (0), $y + (4), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (4), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (4), $z + (1), 18);
$this->level->setBlockDataAt($x + (0), $y + (4), $z + (1), 13);
$this->level->setBlockIdAt($x + (0), $y + (4), $z + (2), 18);
$this->level->setBlockDataAt($x + (0), $y + (4), $z + (2), 13);
$this->level->setBlockIdAt($x + (0), $y + (5), $z + (-2), 18);
$this->level->setBlockDataAt($x + (0), $y + (5), $z + (-2), 13);
$this->level->setBlockIdAt($x + (0), $y + (5), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (5), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (5), $z + (2), 18);
$this->level->setBlockDataAt($x + (0), $y + (5), $z + (2), 13);
$this->level->setBlockIdAt($x + (0), $y + (6), $z + (-1), 18);
$this->level->setBlockDataAt($x + (0), $y + (6), $z + (-1), 13);
$this->level->setBlockIdAt($x + (0), $y + (6), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (6), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (6), $z + (1), 18);
$this->level->setBlockDataAt($x + (0), $y + (6), $z + (1), 13);
$this->level->setBlockIdAt($x + (0), $y + (7), $z + (-3), 18);
$this->level->setBlockDataAt($x + (0), $y + (7), $z + (-3), 13);
$this->level->setBlockIdAt($x + (0), $y + (7), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (7), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (7), $z + (1), 18);
$this->level->setBlockDataAt($x + (0), $y + (7), $z + (1), 13);
$this->level->setBlockIdAt($x + (0), $y + (7), $z + (2), 18);
$this->level->setBlockDataAt($x + (0), $y + (7), $z + (2), 13);
$this->level->setBlockIdAt($x + (0), $y + (8), $z + (-2), 18);
$this->level->setBlockDataAt($x + (0), $y + (8), $z + (-2), 13);
$this->level->setBlockIdAt($x + (0), $y + (8), $z + (-1), 18);
$this->level->setBlockDataAt($x + (0), $y + (8), $z + (-1), 13);
$this->level->setBlockIdAt($x + (0), $y + (8), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (8), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (8), $z + (1), 18);
$this->level->setBlockDataAt($x + (0), $y + (8), $z + (1), 13);
$this->level->setBlockIdAt($x + (0), $y + (9), $z + (-1), 18);
$this->level->setBlockDataAt($x + (0), $y + (9), $z + (-1), 13);
$this->level->setBlockIdAt($x + (0), $y + (9), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (9), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (9), $z + (3), 18);
$this->level->setBlockDataAt($x + (0), $y + (9), $z + (3), 13);
$this->level->setBlockIdAt($x + (0), $y + (10), $z + (-2), 18);
$this->level->setBlockDataAt($x + (0), $y + (10), $z + (-2), 13);
$this->level->setBlockIdAt($x + (0), $y + (10), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (10), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (10), $z + (2), 18);
$this->level->setBlockDataAt($x + (0), $y + (10), $z + (2), 13);
$this->level->setBlockIdAt($x + (0), $y + (11), $z + (-1), 18);
$this->level->setBlockDataAt($x + (0), $y + (11), $z + (-1), 13);
$this->level->setBlockIdAt($x + (0), $y + (11), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (11), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (11), $z + (1), 18);
$this->level->setBlockDataAt($x + (0), $y + (11), $z + (1), 13);
$this->level->setBlockIdAt($x + (0), $y + (12), $z + (-2), 18);
$this->level->setBlockDataAt($x + (0), $y + (12), $z + (-2), 13);
$this->level->setBlockIdAt($x + (0), $y + (12), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (12), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (12), $z + (2), 18);
$this->level->setBlockDataAt($x + (0), $y + (12), $z + (2), 13);
$this->level->setBlockIdAt($x + (0), $y + (13), $z + (-1), 18);
$this->level->setBlockDataAt($x + (0), $y + (13), $z + (-1), 13);
$this->level->setBlockIdAt($x + (0), $y + (13), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (13), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (13), $z + (1), 18);
$this->level->setBlockDataAt($x + (0), $y + (13), $z + (1), 13);
$this->level->setBlockIdAt($x + (0), $y + (14), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (14), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (15), $z + (-1), 18);
$this->level->setBlockDataAt($x + (0), $y + (15), $z + (-1), 13);
$this->level->setBlockIdAt($x + (0), $y + (15), $z + (0), 162);
$this->level->setBlockDataAt($x + (0), $y + (15), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (15), $z + (1), 18);
$this->level->setBlockDataAt($x + (0), $y + (15), $z + (1), 13);
$this->level->setBlockIdAt($x + (0), $y + (16), $z + (0), 18);
$this->level->setBlockDataAt($x + (0), $y + (16), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (17), $z + (-1), 18);
$this->level->setBlockDataAt($x + (0), $y + (17), $z + (-1), 13);
$this->level->setBlockIdAt($x + (0), $y + (17), $z + (0), 18);
$this->level->setBlockDataAt($x + (0), $y + (17), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (17), $z + (1), 18);
$this->level->setBlockDataAt($x + (0), $y + (17), $z + (1), 13);
$this->level->setBlockIdAt($x + (0), $y + (18), $z + (0), 18);
$this->level->setBlockDataAt($x + (0), $y + (18), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (19), $z + (0), 18);
$this->level->setBlockDataAt($x + (0), $y + (19), $z + (0), 13);
$this->level->setBlockIdAt($x + (0), $y + (20), $z + (0), 18);
$this->level->setBlockDataAt($x + (0), $y + (20), $z + (0), 13);
$this->level->setBlockIdAt($x + (1), $y + (0), $z + (0), 162);
$this->level->setBlockDataAt($x + (1), $y + (0), $z + (0), 13);
$this->level->setBlockIdAt($x + (1), $y + (3), $z + (-3), 18);
$this->level->setBlockDataAt($x + (1), $y + (3), $z + (-3), 13);
$this->level->setBlockIdAt($x + (1), $y + (3), $z + (-2), 18);
$this->level->setBlockDataAt($x + (1), $y + (3), $z + (-2), 13);
$this->level->setBlockIdAt($x + (1), $y + (3), $z + (-1), 18);
$this->level->setBlockDataAt($x + (1), $y + (3), $z + (-1), 13);
$this->level->setBlockIdAt($x + (1), $y + (3), $z + (1), 18);
$this->level->setBlockDataAt($x + (1), $y + (3), $z + (1), 13);
$this->level->setBlockIdAt($x + (1), $y + (3), $z + (2), 18);
$this->level->setBlockDataAt($x + (1), $y + (3), $z + (2), 13);
$this->level->setBlockIdAt($x + (1), $y + (4), $z + (0), 18);
$this->level->setBlockDataAt($x + (1), $y + (4), $z + (0), 13);
$this->level->setBlockIdAt($x + (1), $y + (5), $z + (0), 18);
$this->level->setBlockDataAt($x + (1), $y + (5), $z + (0), 13);
$this->level->setBlockIdAt($x + (1), $y + (5), $z + (1), 18);
$this->level->setBlockDataAt($x + (1), $y + (5), $z + (1), 13);
$this->level->setBlockIdAt($x + (1), $y + (5), $z + (2), 18);
$this->level->setBlockDataAt($x + (1), $y + (5), $z + (2), 13);
$this->level->setBlockIdAt($x + (1), $y + (5), $z + (3), 18);
$this->level->setBlockDataAt($x + (1), $y + (5), $z + (3), 13);
$this->level->setBlockIdAt($x + (1), $y + (6), $z + (-3), 18);
$this->level->setBlockDataAt($x + (1), $y + (6), $z + (-3), 13);
$this->level->setBlockIdAt($x + (1), $y + (6), $z + (-1), 18);
$this->level->setBlockDataAt($x + (1), $y + (6), $z + (-1), 13);
$this->level->setBlockIdAt($x + (1), $y + (6), $z + (0), 18);
$this->level->setBlockDataAt($x + (1), $y + (6), $z + (0), 13);
$this->level->setBlockIdAt($x + (1), $y + (6), $z + (1), 18);
$this->level->setBlockDataAt($x + (1), $y + (6), $z + (1), 13);
$this->level->setBlockIdAt($x + (1), $y + (6), $z + (2), 18);
$this->level->setBlockDataAt($x + (1), $y + (6), $z + (2), 13);
$this->level->setBlockIdAt($x + (1), $y + (7), $z + (-2), 18);
$this->level->setBlockDataAt($x + (1), $y + (7), $z + (-2), 13);
$this->level->setBlockIdAt($x + (1), $y + (8), $z + (-2), 18);
$this->level->setBlockDataAt($x + (1), $y + (8), $z + (-2), 13);
$this->level->setBlockIdAt($x + (1), $y + (8), $z + (-1), 18);
$this->level->setBlockDataAt($x + (1), $y + (8), $z + (-1), 13);
$this->level->setBlockIdAt($x + (1), $y + (8), $z + (0), 18);
$this->level->setBlockDataAt($x + (1), $y + (8), $z + (0), 13);
$this->level->setBlockIdAt($x + (1), $y + (8), $z + (1), 18);
$this->level->setBlockDataAt($x + (1), $y + (8), $z + (1), 13);
$this->level->setBlockIdAt($x + (1), $y + (8), $z + (2), 18);
$this->level->setBlockDataAt($x + (1), $y + (8), $z + (2), 13);
$this->level->setBlockIdAt($x + (1), $y + (9), $z + (1), 18);
$this->level->setBlockDataAt($x + (1), $y + (9), $z + (1), 5);
$this->level->setBlockIdAt($x + (1), $y + (10), $z + (-1), 18);
$this->level->setBlockDataAt($x + (1), $y + (10), $z + (-1), 13);
$this->level->setBlockIdAt($x + (1), $y + (10), $z + (1), 18);
$this->level->setBlockDataAt($x + (1), $y + (10), $z + (1), 13);
$this->level->setBlockIdAt($x + (1), $y + (11), $z + (0), 18);
$this->level->setBlockDataAt($x + (1), $y + (11), $z + (0), 13);
$this->level->setBlockIdAt($x + (1), $y + (12), $z + (1), 18);
$this->level->setBlockDataAt($x + (1), $y + (12), $z + (1), 13);
$this->level->setBlockIdAt($x + (1), $y + (13), $z + (0), 18);
$this->level->setBlockDataAt($x + (1), $y + (13), $z + (0), 13);
$this->level->setBlockIdAt($x + (1), $y + (14), $z + (-1), 18);
$this->level->setBlockDataAt($x + (1), $y + (14), $z + (-1), 13);
$this->level->setBlockIdAt($x + (1), $y + (14), $z + (0), 18);
$this->level->setBlockDataAt($x + (1), $y + (14), $z + (0), 13);
$this->level->setBlockIdAt($x + (1), $y + (14), $z + (1), 18);
$this->level->setBlockDataAt($x + (1), $y + (14), $z + (1), 13);
$this->level->setBlockIdAt($x + (1), $y + (16), $z + (-1), 18);
$this->level->setBlockDataAt($x + (1), $y + (16), $z + (-1), 13);
$this->level->setBlockIdAt($x + (1), $y + (16), $z + (0), 18);
$this->level->setBlockDataAt($x + (1), $y + (16), $z + (0), 13);
$this->level->setBlockIdAt($x + (1), $y + (17), $z + (0), 18);
$this->level->setBlockDataAt($x + (1), $y + (17), $z + (0), 13);
$this->level->setBlockIdAt($x + (2), $y + (2), $z + (-3), 18);
$this->level->setBlockDataAt($x + (2), $y + (2), $z + (-3), 13);
$this->level->setBlockIdAt($x + (2), $y + (3), $z + (-2), 18);
$this->level->setBlockDataAt($x + (2), $y + (3), $z + (-2), 13);
$this->level->setBlockIdAt($x + (2), $y + (3), $z + (0), 18);
$this->level->setBlockDataAt($x + (2), $y + (3), $z + (0), 13);
$this->level->setBlockIdAt($x + (2), $y + (3), $z + (3), 18);
$this->level->setBlockDataAt($x + (2), $y + (3), $z + (3), 13);
$this->level->setBlockIdAt($x + (2), $y + (5), $z + (-2), 18);
$this->level->setBlockDataAt($x + (2), $y + (5), $z + (-2), 13);
$this->level->setBlockIdAt($x + (2), $y + (5), $z + (0), 18);
$this->level->setBlockDataAt($x + (2), $y + (5), $z + (0), 13);
$this->level->setBlockIdAt($x + (2), $y + (6), $z + (-1), 18);
$this->level->setBlockDataAt($x + (2), $y + (6), $z + (-1), 13);
$this->level->setBlockIdAt($x + (2), $y + (6), $z + (1), 18);
$this->level->setBlockDataAt($x + (2), $y + (6), $z + (1), 13);
$this->level->setBlockIdAt($x + (2), $y + (7), $z + (-2), 18);
$this->level->setBlockDataAt($x + (2), $y + (7), $z + (-2), 13);
$this->level->setBlockIdAt($x + (2), $y + (8), $z + (-1), 18);
$this->level->setBlockDataAt($x + (2), $y + (8), $z + (-1), 13);
$this->level->setBlockIdAt($x + (2), $y + (9), $z + (-1), 18);
$this->level->setBlockDataAt($x + (2), $y + (9), $z + (-1), 13);
$this->level->setBlockIdAt($x + (2), $y + (9), $z + (1), 18);
$this->level->setBlockDataAt($x + (2), $y + (9), $z + (1), 13);
$this->level->setBlockIdAt($x + (2), $y + (10), $z + (0), 18);
$this->level->setBlockDataAt($x + (2), $y + (10), $z + (0), 13);
$this->level->setBlockIdAt($x + (2), $y + (12), $z + (0), 18);
$this->level->setBlockDataAt($x + (2), $y + (12), $z + (0), 13);
$this->level->setBlockIdAt($x + (2), $y + (13), $z + (1), 18);
$this->level->setBlockDataAt($x + (2), $y + (13), $z + (1), 13);
$this->level->setBlockIdAt($x + (3), $y + (2), $z + (0), 18);
$this->level->setBlockDataAt($x + (3), $y + (2), $z + (0), 13);
$this->level->setBlockIdAt($x + (3), $y + (3), $z + (1), 18);
$this->level->setBlockDataAt($x + (3), $y + (3), $z + (1), 13);
$this->level->setBlockIdAt($x + (3), $y + (4), $z + (0), 18);
$this->level->setBlockDataAt($x + (3), $y + (4), $z + (0), 13);
$this->level->setBlockIdAt($x + (3), $y + (5), $z + (1), 18);
$this->level->setBlockDataAt($x + (3), $y + (5), $z + (1), 13);
$this->level->setBlockIdAt($x + (3), $y + (7), $z + (-1), 18);
$this->level->setBlockDataAt($x + (3), $y + (7), $z + (-1), 13);
$this->level->setBlockIdAt($x + (3), $y + (9), $z + (-1), 18);
$this->level->setBlockDataAt($x + (3), $y + (9), $z + (-1), 13);
$this->level->setBlockIdAt($x + (4), $y + (2), $z + (1), 18);
$this->level->setBlockDataAt($x + (4), $y + (2), $z + (1), 13);
	   }
    }